"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import dj_database_url
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(name: str, default: bool = False) -> bool:
    v = os.environ.get(name)
    if v is None:
        return default
    return v.strip().lower() in ("1", "true", "yes", "on", "t", "y")

# Identify if we are in production
IS_PRODUCTION = os.environ.get("DJANGO_ENV", "").lower() == "production" or os.environ.get("RENDER", "") == "true"


# SECURITY WARNING: set DJANGO_SECRET_KEY in production.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-dev-only-uiz@t@az%7#u$cne*)1x24-c64j)44)%+6()h=$fvbag*d414_",
)

DEBUG = _env_bool("DJANGO_DEBUG", default=not IS_PRODUCTION)

from django.core.exceptions import ImproperlyConfigured
if IS_PRODUCTION:
    if DEBUG:
        raise ImproperlyConfigured("CRITICAL: DEBUG=True is not allowed in the production environment!")
    if SECRET_KEY.startswith("django-insecure"):
        raise ImproperlyConfigured("CRITICAL: Default django-insecure secret key is strictly forbidden in production!")
    if not os.environ.get("DATABASE_URL"):
        raise ImproperlyConfigured("CRITICAL: DATABASE_URL is strictly required in production!")
    if not os.environ.get("REDIS_URL"):
        raise ImproperlyConfigured("CRITICAL: REDIS_URL is strictly required in production!")

_hosts_raw = os.environ.get("DJANGO_ALLOWED_HOSTS", "").strip()
if _hosts_raw:
    ALLOWED_HOSTS = [h.strip() for h in _hosts_raw.split(",") if h.strip()]
elif DEBUG:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "[::1]"]
else:
    ALLOWED_HOSTS = []

_csrf_raw = os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").strip()
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in _csrf_raw.split(",") if o.strip()
]

_cors_raw = os.environ.get("DJANGO_CORS_ALLOWED_ORIGINS", "").strip()
CORS_ALLOWED_ORIGINS = [
    o.strip() for o in _cors_raw.split(",") if o.strip()
]
# Removed CORS_ALLOW_ALL_ORIGINS fallback to enforce strict whitelist

# HTTPS & Proxy Enforcement
SECURE_SSL_REDIRECT = _env_bool("SECURE_SSL_REDIRECT", default=IS_PRODUCTION)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Secure Headers
if IS_PRODUCTION:
    SECURE_HSTS_SECONDS = 31536000 # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
SECURE_REFERRER_POLICY = "same-origin"

# Secure Cookies
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = "Lax"

# FastAPI cognitive inference (used by WebSocket consumer).
ML_SERVICE_URL = os.environ.get(
    "ML_SERVICE_URL",
    "http://127.0.0.1:8001/api/infer",
)

# Dev-only: allow WebSocket telemetry without JWT (uses shared `telemetry_dev` user).
# Never enable in production. Requires DEBUG=True.
ALLOW_DEV_INSECURE_TELEMETRY = (
    _env_bool("ALLOW_DEV_INSECURE_TELEMETRY", default=False) and DEBUG
)

WS_MAX_MESSAGES_PER_MIN = int(os.environ.get("WS_MAX_MESSAGES_PER_MIN", 30))
WS_MAX_PAYLOAD_BYTES = int(os.environ.get("WS_MAX_PAYLOAD_BYTES", 51200)) # 50KB default


INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "channels",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "django_prometheus",
    "gateway",
]

MIDDLEWARE = [
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_prometheus.middleware.PrometheusAfterMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"
ASGI_APPLICATION = "core.asgi.application"

# Django Caching
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/0"),
    }
}

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/0")],
        },
    },
}


import urllib.parse

_db_url = os.environ.get("DATABASE_URL", "").strip()

if _db_url:
    # If using Neon, we want to ensure sslmode=require is set in the URL or via ssl_require
    _ssl_require = "neon.tech" in _db_url
    
    DATABASES = {
        "default": dj_database_url.config(
            default=_db_url,
            conn_max_age=600,
            ssl_require=_ssl_require
        )
    }
else:
    # Local dev fallback
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle"
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "10/min",
        "user": "60/min",
        "ws_ticket": "10/min",
    },
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Cognitive Load AI Gateway API",
    "DESCRIPTION": "API for cognitive session tracking and telemetry",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}


AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Observability & Log Sanitization
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "sensitive_data_filter": {
            "()": "core.log_filters.SensitiveDataFilter",
        },
    },
    "formatters": {
        "structured": {
            "()": "pythonjsonlogger.jsonlogger.JsonFormatter",
            "format": "%(levelname)s %(asctime)s %(name)s %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "filters": ["sensitive_data_filter"],
            "formatter": "structured",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": os.environ.get("DJANGO_LOG_LEVEL", "INFO"),
    },
}

# Sentry Configuration
# pyrefly: ignore [missing-import]
import sentry_sdk
# pyrefly: ignore [missing-import]
from sentry_sdk.integrations.django import DjangoIntegration

def sentry_before_send(event, hint):
    # Scrub PII
    if "request" in event and "data" in event["request"]:
        # Scrub telemetry payloads
        data = event["request"]["data"]
        if isinstance(data, dict):
            if "keyboard" in data:
                data["keyboard"] = "[FILTERED]"
            if "mouse" in data:
                data["mouse"] = "[FILTERED]"
    return event

sentry_sdk.init(
    dsn=os.environ.get("SENTRY_DSN", ""),
    integrations=[DjangoIntegration()],
    traces_sample_rate=1.0,
    send_default_pii=False,
    before_send=sentry_before_send,
    environment=os.environ.get("DJANGO_ENV", "development"),
)
