# Generated by Django 4.2.7 on 2026-05-11 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CognitivePrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("focus_score", models.FloatField()),
                ("fatigue_score", models.FloatField()),
                ("predicted_state", models.CharField(max_length=50)),
                ("confidence", models.FloatField()),
                (
                    "model_version",
                    models.CharField(default="v1_heuristic", max_length=50),
                ),
                ("top_factors", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="CognitiveSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("average_focus", models.FloatField(blank=True, null=True)),
                ("peak_fatigue", models.FloatField(blank=True, null=True)),
                ("total_interventions", models.IntegerField(default=0)),
                ("session_summary", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cognitive_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HumanFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_label", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "prediction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gateway.cognitiveprediction",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="gateway.cognitivesession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompressedTelemetry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("keyboard_data", models.JSONField(default=dict)),
                ("mouse_data", models.JSONField(default=dict)),
                ("activity_data", models.JSONField(default=dict)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemetry",
                        to="gateway.cognitivesession",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cognitiveprediction",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="predictions",
                to="gateway.cognitivesession",
            ),
        ),
    ]
