# Generated by Django 4.2.7 on 2026-05-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gateway", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cognitiveprediction",
            name="batch_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="humanfeedback",
            name="features_snapshot",
            field=models.JSONField(default=dict),
        ),
    ]
