# Generated by Django 4.2.7 on 2026-05-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gateway", "0002_cognitiveprediction_batch_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cognitiveprediction",
            name="model_source",
            field=models.CharField(default="heuristic", max_length=50),
        ),
    ]
