# Generated by Django 5.2.14 on 2026-05-12 05:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gateway", "0003_cognitiveprediction_model_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="cognitivesession",
            name="ended_reason",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="cognitivesession",
            name="last_activity_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 5, 12, 5, 2, 42, 877916, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cognitivesession",
            name="status",
            field=models.CharField(default="active", max_length=20),
        ),
    ]
