# Generated by Django 4.2.7 on 2026-05-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gateway", "0004_cognitivesession_ended_reason_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="humanfeedback",
            name="user_label",
        ),
        migrations.AddField(
            model_name="humanfeedback",
            name="confidence_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="humanfeedback",
            name="fatigue_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="humanfeedback",
            name="feature_schema_version",
            field=models.CharField(default="v1.0", max_length=50),
        ),
        migrations.AddField(
            model_name="humanfeedback",
            name="focus_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="humanfeedback",
            name="label_source",
            field=models.CharField(default="self-report", max_length=50),
        ),
        migrations.AddField(
            model_name="humanfeedback",
            name="prompt_response_delay_ms",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="humanfeedback",
            name="prompt_trigger_type",
            field=models.CharField(default="random", max_length=50),
        ),
        migrations.AddField(
            model_name="humanfeedback",
            name="tab_switch_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="humanfeedback",
            name="visibility_state",
            field=models.CharField(default="visible", max_length=50),
        ),
        migrations.AddField(
            model_name="humanfeedback",
            name="workload_score",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
