# Generated by Django 4.2.7 on 2026-05-18 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gateway", "0005_remove_humanfeedback_user_label_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPrivacyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telemetry_consent", models.BooleanField(default=False)),
                ("privacy_mode", models.BooleanField(default=False)),
                ("consent_timestamp", models.DateTimeField(auto_now_add=True)),
                ("consent_version", models.CharField(default="1.0", max_length=50)),
                ("deletion_requested_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="privacy_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrivacyAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("CONSENT_GRANTED", "Consent Granted"),
                            ("CONSENT_REVOKED", "Consent Revoked"),
                            ("PRIVACY_MODE_ENABLED", "Privacy Mode Enabled"),
                            ("PRIVACY_MODE_DISABLED", "Privacy Mode Disabled"),
                            ("DELETION_REQUESTED", "Deletion Requested"),
                            ("DELETION_COMPLETED", "Deletion Completed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="privacy_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
